INSERT INTO `uproductssers` (`user_id`,`user_type`,`role_type`,`username`,`email`,`password`,`create_time`,`verified_time`,`eula_time`) VALUES (UNHEX(REPLACE('52d8e099-9941-11e8-ab1c-080027d981a5','-','')),1,'SUPER','ohm-super','web-master@ohmbeads.com','$2a$10$q0E3CMqI2Z3KRQC197mTxOLPJSsm8nxV68nKkYiP4OeVyrGCiNU4m',current_timestamp(),NULL,NULL);
INSERT INTO `users` (`user_id`,`user_type`,`role_type`,`username`,`email`,`password`,`create_time`,`verified_time`,`eula_time`) VALUES (UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')),1,'ADMIN','ohm-admin','support@ohmbeads.com','$2a$10$L14n61BYtm6DmkdhicUReeeTDSqhLWWdcs4xxnhUszS5RaqoH1rt.',current_timestamp(),NULL,NULL);
INSERT INTO `users` (`user_id`,`user_type`,`role_type`,`username`,`email`,`password`,`create_time`,`verified_time`,`eula_time`) VALUES (UNHEX(REPLACE('6c7acae9-9941-11e8-ab1c-080027d981a5','-','')),1,'USER','ohm-user','user1@ohmbeads.com','$2a$10$x5gYlifATRZf1hLyOS3/reXkS2QNKo.IPGVjkL9da91yB/a7du8Gi',current_timestamp(),NULL,NULL);

INSERT INTO `brands` (`brand_id`,`name`,`create_time`,`created_by`) VALUES (1,'OHM',current_timestamp(), UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `brands` (`brand_id`,`name`,`create_time`,`created_by`) VALUES (2,'Pandora',current_timestamp(), UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `brands` (`brand_id`,`name`,`create_time`,`created_by`) VALUES (3,'Trollbeads',current_timestamp(), UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `brands` (`brand_id`,`name`,`create_time`,`created_by`) VALUES (4,'Artisans',current_timestamp(), UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));

INSERT INTO `release_types` (`release_code`,`name`) VALUES ('LE','Limited Edition');
INSERT INTO `release_types` (`release_code`,`name`) VALUES ('SE','Special Edition');
INSERT INTO `release_types` (`release_code`,`name`) VALUES ('SLE','Special Limited Edition');
INSERT INTO `release_types` (`release_code`,`name`) VALUES ('UR','Unreleased');
INSERT INTO `release_types` (`release_code`,`name`) VALUES ('WW','World-wide');

-- INSERT INTO `products` (`sku`,`name`,`create_time`,`created_by`,`map`,`release_type_code`,`brand_id`,`release_date`,`discontinued_date`,`soldout_date`) VALUES ('AAA004','ALASKA KING CRAB',current_timestamp(),UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')),25.50,'WW',1,'2018-07-14',NULL,NULL);
-- INSERT INTO `products` (`sku`,`name`,`create_time`,`created_by`,`map`,`release_type_code`,`brand_id`,`release_date`,`discontinued_date`,`soldout_date`) VALUES ('AAM002','SOUSAPHONE',current_timestamp(),UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')),20.00,'WW',1,'2018-07-14',NULL,NULL);
-- INSERT INTO `products` (`sku`,`name`,`create_time`,`created_by`,`map`,`release_type_code`,`brand_id`,`release_date`,`discontinued_date`,`soldout_date`) VALUES ('AAP019','ATOMIC',current_timestamp(),UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')),20.00,'WW',1,'2018-07-14',NULL,NULL);
-- 
-- INSERT INTO `images` (`image_id`,`reference`,`sku`,`created_by`) VALUES (UNHEX(REPLACE(UUID(),'-','')),'https://www.ohmbeads.com/ohm2/media/product/a6e/alaska-king-crab-748.jpg','AAA004',UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
-- INSERT INTO `images` (`image_id`,`reference`,`sku`,`created_by`) VALUES (UNHEX(REPLACE(UUID(),'-','')),'https://www.ohmbeads.com/ohm2/media/product/bf3/sousaphone-643.jpg','AAM002',UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
-- INSERT INTO `images` (`image_id`,`reference`,`sku`,`created_by`) VALUES (UNHEX(REPLACE(UUID(),'-','')),'https://www.ohmbeads.com/ohm2/media/product/7d1/atomic-024.jpg','AAP019',UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
-- 
-- INSERT INTO `user_products` (`user_id`, `sku`, `created_by`, `quantity`, `unit_price`) VALUES ('1', 'AAA004', '1', '15', '50.00');
-- INSERT INTO `user_products` (`user_id`, `sku`, `created_by`, `quantity`, `unit_price`) VALUES ('1', 'AAM002', '1', '12', '29.99');
-- INSERT INTO `user_products` (`user_id`, `sku`, `created_by`, `quantity`, `unit_price`) VALUES ('1', 'AAP019', '1', '8', '47.99');
-- 
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AED', 'UAE Dirham');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AFN', 'Afghani');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ALL', 'Lek');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AMD', 'Armenian Dram');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ANG', 'Netherlands Antillean Guilder');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AOA', 'Kwanza');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ARS', 'Argentine Peso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AUD', 'Australian Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AWG', 'Aruban Florin');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('AZN', 'Azerbaijan Manat');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BAM', 'Convertible Mark');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BBD', 'Barbados Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BDT', 'Taka');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BGN', 'Bulgarian Lev');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BHD', 'Bahraini Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BIF', 'Burundi Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BMD', 'Bermudian Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BND', 'Brunei Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BOB', 'Boliviano');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BOV', 'Mvdol');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BRL', 'Brazilian Real');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BSD', 'Bahamian Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BTN', 'Ngultrum');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BWP', 'Pula');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BYN', 'Belarusian Ruble');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('BZD', 'Belize Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CAD', 'Canadian Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CDF', 'Congolese Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CHE', 'WIR Euro');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CHF', 'Swiss Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CHW', 'WIR Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CLF', 'Unidad de Fomento');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CLP', 'Chilean Peso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CNY', 'Yuan Renminbi');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('COP', 'Colombian Peso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('COU', 'Unidad de Valor Real');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CRC', 'Costa Rican Colon');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CUC', 'Peso Convertible');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CUP', 'Cuban Peso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CVE', 'Cabo Verde Escudo');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('CZK', 'Czech Koruna');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('DJF', 'Djibouti Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('DKK', 'Danish Krone');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('DOP', 'Dominican Peso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('DZD', 'Algerian Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('EGP', 'Egyptian Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ERN', 'Nakfa');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ETB', 'Ethiopian Birr');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('EUR', 'Euro');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('FJD', 'Fiji Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('FKP', 'Falkland Islands Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GBP', 'Pound Sterling');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GEL', 'Lari');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GHS', 'Ghana Cedi');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GIP', 'Gibraltar Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GMD', 'Dalasi');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GNF', 'Guinean Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GTQ', 'Quetzal');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('GYD', 'Guyana Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('HKD', 'Hong Kong Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('HNL', 'Lempira');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('HRK', 'Kuna');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('HTG', 'Gourde');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('HUF', 'Forint');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('IDR', 'Rupiah');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ILS', 'New Israeli Sheqel');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('INR', 'Indian Rupee');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('IQD', 'Iraqi Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('IRR', 'Iranian Rial');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ISK', 'Iceland Krona');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('JMD', 'Jamaican Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('JOD', 'Jordanian Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('JPY', 'Yen');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KES', 'Kenyan Shilling');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KGS', 'Som');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KHR', 'Riel');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KMF', 'Comorian Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KPW', 'North Korean Won');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KRW', 'Won');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KWD', 'Kuwaiti Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KYD', 'Cayman Islands Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('KZT', 'Tenge');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('LAK', 'Lao Kip');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('LBP', 'Lebanese Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('LKR', 'Sri Lanka Rupee');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('LRD', 'Liberian Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('LSL', 'Loti');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('LYD', 'Libyan Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MAD', 'Moroccan Dirham');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MDL', 'Moldovan Leu');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MGA', 'Malagasy Ariary');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MKD', 'Denar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MMK', 'Kyat');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MNT', 'Tugrik');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MOP', 'Pataca');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MRU', 'Ouguiya');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MUR', 'Mauritius Rupee');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MVR', 'Rufiyaa');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MWK', 'Malawi Kwacha');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MXN', 'Mexican Peso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MXV', 'Mexican Unidad de Inversion (UDI)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MYR', 'Malaysian Ringgit');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('MZN', 'Mozambique Metical');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('NAD', 'Namibia Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('NGN', 'Naira');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('NIO', 'Cordoba Oro');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('NOK', 'Norwegian Krone');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('NPR', 'Nepalese Rupee');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('NZD', 'New Zealand Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('OMR', 'Rial Omani');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PAB', 'Balboa');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PEN', 'Sol');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PGK', 'Kina');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PHP', 'Philippine Piso');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PKR', 'Pakistan Rupee');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PLN', 'Zloty');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('PYG', 'Guarani');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('QAR', 'Qatari Rial');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('RON', 'Romanian Leu');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('RSD', 'Serbian Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('RUB', 'Russian Ruble');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('RWF', 'Rwanda Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SAR', 'Saudi Riyal');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SBD', 'Solomon Islands Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SCR', 'Seychelles Rupee');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SDG', 'Sudanese Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SEK', 'Swedish Krona');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SGD', 'Singapore Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SHP', 'Saint Helena Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SLL', 'Leone');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SOS', 'Somali Shilling');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SRD', 'Surinam Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SSP', 'South Sudanese Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('STN', 'Dobra');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SVC', 'El Salvador Colon');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SYP', 'Syrian Pound');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('SZL', 'Lilangeni');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('THB', 'Baht');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TJS', 'Somoni');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TMT', 'Turkmenistan New Manat');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TND', 'Tunisian Dinar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TOP', 'Pa’anga');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TRY', 'Turkish Lira');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TTD', 'Trinidad and Tobago Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TWD', 'New Taiwan Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('TZS', 'Tanzanian Shilling');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('UAH', 'Hryvnia');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('UGX', 'Uganda Shilling');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('USD', 'US Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('USN', 'US Dollar (Next day)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('UYI', 'Uruguay Peso en Unidades Indexadas (UI)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('UYU', 'Peso Uruguayo');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('UZS', 'Uzbekistan Sum');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('VEF', 'Bolívar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('VND', 'Dong');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('VUV', 'Vatu');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('WST', 'Tala');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XAF', 'CFA Franc BEAC');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XAG', 'Silver');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XAU', 'Gold');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XBA', 'Bond Markets Unit European Composite Unit (EURCO)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XCD', 'East Caribbean Dollar');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XDR', 'SDR (Special Drawing Right)');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XOF', 'CFA Franc BCEAO');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XPD', 'Palladium');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XPF', 'CFP Franc');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XPT', 'Platinum');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XSU', 'Sucre');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XTS', 'Codes specifically reserved for testing purposes');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XUA', 'ADB Unit of Account');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('XXX', 'The codes assigned for transactions where no currency is involved');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('YER', 'Yemeni Rial');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ZAR', 'Rand');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ZMW', 'Zambian Kwacha');
INSERT INTO `optopus`.`currencies` (`currency_code`, `name`) VALUES ('ZWL', 'Zimbabwe Dollar');

INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('Great Lake Boutiques', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('Amazon', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM in Europe', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM in Australia', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM in Russia', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM in Canada', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM in Taiwan', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM in Thailand', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM Stuff', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('OHM Together', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
INSERT INTO `optopus`.`sellers` (`seller`, `created_by`) VALUES ('Other', UNHEX(REPLACE('6556350a-9941-11e8-ab1c-080027d981a5','-','')));
